/* Offline level generator for Dice Match 3D.
   Builds feasible dice sets, scatters them, verifies full clearability
   with the solver, and writes www/levels.js. Run: node scripts/gen-levels.js */
const path = require("path");
const fs = require("fs");
const E = require(path.join(__dirname, "..", "www", "engine.js"));

const NUM = 50;

// Difficulty curve: the board widens smoothly (3x3 -> 6x6), dice count grows
// with it, and higher top-values (which need bigger same-value clusters to
// clear, Devil-Dice style) are introduced only in the later tiers.
function spec(L) {
  if (L <= 5)  return { rows: 3, cols: 3, allowed: [2, 3],          K: 4,  parMin: 2,  parMax: 9,  maxNodes: 90000  };
  if (L <= 12) return { rows: 4, cols: 4, allowed: [2, 3],          K: 6,  parMin: 3,  parMax: 12, maxNodes: 120000 };
  if (L <= 20) return { rows: 4, cols: 4, allowed: [2, 3, 4],       K: 7,  parMin: 5,  parMax: 14, maxNodes: 150000 };
  if (L <= 30) return { rows: 4, cols: 5, allowed: [2, 3, 4],       K: 9,  parMin: 6,  parMax: 17, maxNodes: 200000 };
  if (L <= 40) return { rows: 5, cols: 5, allowed: [2, 3, 4, 5],    K: 11, parMin: 8,  parMax: 21, maxNodes: 300000 };
  return                { rows: 6, cols: 6, allowed: [2, 3, 4, 5, 6], K: 14, parMin: 10, parMax: 26, maxNodes: 450000 };
}

// random partition of K where each part is an allowed value (so each
// part can form a self-clearing group of that many same-valued dice).
function composition(K, allowed) {
  for (let tries = 0; tries < 200; tries++) {
    const parts = [];
    let rem = K;
    let ok = true;
    while (rem > 0) {
      const cand = allowed.filter((v) => v <= rem && rem - v !== 1);
      if (cand.length === 0) { ok = false; break; }
      parts.push(cand[(Math.random() * cand.length) | 0]);
      rem -= parts[parts.length - 1];
    }
    if (ok && rem === 0) return parts;
  }
  return null;
}

function randInt(n) { return (Math.random() * n) | 0; }

function buildCandidate(s) {
  const parts = composition(s.K, s.allowed);
  if (!parts) return null;
  // dice list: each part v contributes v dice of value v
  const values = [];
  for (const v of parts) for (let i = 0; i < v; i++) values.push(v);
  if (values.length > s.rows * s.cols - 1) return null; // need room + char

  // random distinct cells
  const cells = [];
  for (let r = 0; r < s.rows; r++) for (let c = 0; c < s.cols; c++) cells.push([r, c]);
  for (let i = cells.length - 1; i > 0; i--) { const j = randInt(i + 1); [cells[i], cells[j]] = [cells[j], cells[i]]; }

  const dice = [];
  for (let i = 0; i < values.length; i++) {
    const [r, c] = cells[i];
    const d = E.randomOrientation(values[i]);
    dice.push({ r, c, top: d.top, north: d.north, east: d.east });
  }
  const charCell = cells[randInt(values.length)]; // char rides one of the dice
  const level = { rows: s.rows, cols: s.cols, dice, char: { r: charCell[0], c: charCell[1] } };

  // reject if any immediate match at start (puzzle must begin stable)
  const st = E.stateFromLevel(level);
  if (E.findClears(st).length > 0) return null;
  return level;
}

function verifySolution(level, sol) {
  let st = E.stateFromLevel(level);
  for (const d of sol) {
    const res = E.applyMove(st, d);
    if (!res) return false;
    st = res.next;
  }
  return E.isEmpty(st);
}

function generateLevel(L) {
  let s = spec(L);
  for (let relax = 0; relax < 6; relax++) {
    const attempts = 6000;
    for (let a = 0; a < attempts; a++) {
      const cand = buildCandidate(s);
      if (!cand) continue;
      const sol = E.solve(E.stateFromLevel(cand), { maxNodes: s.maxNodes, maxDepth: s.parMax + 1 });
      if (!sol) continue;
      if (sol.length < s.parMin || sol.length > s.parMax) continue;
      if (!verifySolution(cand, sol)) continue; // belt-and-suspenders
      cand.par = sol.length;
      return cand;
    }
    // relax: smaller board pressure / fewer dice / wider par
    s = { ...s, K: Math.max(3, s.K - 1), parMin: Math.max(2, s.parMin - 2), parMax: s.parMax + 3 };
  }
  return null;
}

const levels = [];
const t0 = Date.now();
for (let L = 1; L <= NUM; L++) {
  const lv = generateLevel(L);
  if (!lv) { console.error(`level ${L}: FAILED to generate`); process.exit(1); }
  levels.push(lv);
  process.stdout.write(`L${L}: ${lv.rows}x${lv.cols} dice=${lv.dice.length} par=${lv.par}\n`);
}
console.log(`\ngenerated ${levels.length} levels in ${((Date.now() - t0) / 1000).toFixed(1)}s`);

const out =
  "// Auto-generated by scripts/gen-levels.js — every level is solver-verified solvable.\n" +
  "window.LEVELS = " + JSON.stringify(levels) + ";\n";
fs.writeFileSync(path.join(__dirname, "..", "www", "levels.js"), out);
console.log("wrote www/levels.js");
